apiVersion: v1
kind: Pod
metadata:
  name: suite-postgres
  labels:
    name: test
spec:
  containers:
  - name: suite-postgres
    image: postgres
    env:
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: pg.user
    - name: DB_PASS
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: pg.pwd
